### PR TITLE
Rearranged files and folders structure

### PR DESCRIPTION
**Pull request by vertxt**
- Added a folder called "screens", storing all the app main screens code (Calculator, Converter).

### CODE REVIEW

**Review by maqmatic — CHANGES_REQUESTED** [review]
I think `Styles.ts` and `Types.ts` both should the `.tsx` extension instead.

Take a look at [this](https://stackoverflow.com/questions/56871384/what-is-the-difference-between-ts-and-tsx-extensions-both-are-used-as-extensi):

> Use .ts for pure TypeScript files.
> Use .tsx for files which contain JSX.
> For example, a React component would be .tsx, but a file containing helper functions would be .ts.

Aside from that, everything looks good! I will merge right after the change.

**Comment by vertxt** [comment]
In those files, I didn't use any JSX elements, just exported pure TS elements. How as you suggested, renaming them could make it clearer. I will implement your requested changes right away.

**Comment by maqmatic** [comment]
> In those files, I didn't use any JSX elements, just exported pure TS elements. How as you suggested, renaming them could make it clearer. I will implement your requested changes right away.

Not sure if the extension of the files in `utils` also need to be changed to `.ts` because they seem to be containing a bunch of helper functions, right?

**Comment by vertxt** [comment]
They will work fine, cause there aren't any JSX elements in those files.

**Comment by maqmatic** [comment]
> They will work fine, cause there aren't any JSX elements in those files.

Yeah they're totally fine, I just wanna stick to the good practices.

**Comment by vertxt** [comment]
Yeh it really depends on your choice, I think we should keep up using the old names with .tsx extensions.

**Review by maqmatic — APPROVED** [review]

**Pull request merged**
